# Generated by Django 5.0.2 on 2024-02-25 10:59

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='cat', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/Category.jpg')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
