# Generated by Django 5.0.2 on 2024-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/Banner.jpg')),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('deal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/slider.jpg')),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('deal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='subbanner_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/SubBanner_1.jpg')),
                ('free_shipping_from', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subbanner_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/SubBanner_2.jpg')),
                ('free_shipping_from', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
    ]
