# Generated by Django 5.0.2 on 2024-02-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_banner_deal_alter_slider_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subbanner_2',
        ),
    ]
