# Generated by Django 5.0.2 on 2024-06-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=100, unique=True),
        ),
    ]
