# Generated by Django 5.0.2 on 2024-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_account_email_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
